### ISSUE TITLE
7. Host a Webpage

### ISSUE THREAD

**Issue by alexdseo** [alexdseo/Visualization-App-on-World-Events#10]
Showcase our work including all entities distribution, dynamical maps, as well as the additional analysis and explanations.

**Comment by alexdseo** [comment]
Host with github.io and use Jekyll

**Comment by hsuanchu** [comment]
Alternative option:
Created a website here: www.nostrongfeelings.com

**Comment by alexdseo** [comment]
https://alexdseo.github.io/Visualization-App-on-World-Events/
