### ISSUE TITLE
3. Text preprocessing

### ISSUE THREAD

**Issue by alexdseo** [alexdseo/Visualization-App-on-World-Events#3]
Save the extracted text into a preferable format that will allow you to fetch the
text again when needed. It can be saved as a JSON, or as a DataFrame and then
pickled, or in the set of textual files properly named and organized in the folders, so you know the date and the news source of each text.

Make sure to showcase that script can remove the unnecessary extra text from the menus or the ads.

**Comment by auderoy** [comment]
Done & code added at [text processing code](https://github.com/alexdseo/Visualization-App-on-World-Events/blob/master/text_processing.ipynb)

Result saved as cleaned_text.zip in Google Drive
