### ISSUE TITLE
5. Geo-parsing

### ISSUE THREAD

**Issue by alexdseo** [alexdseo/Visualization-App-on-World-Events#8]
Perform the geoparsing on GPE and LOC entities. Use Python GeoPy library. Be cognizant of the potential API limits and make sure to optimize for the number of queries.

**Comment by auderoy** [comment]
Please share example of GPE/LOC entities/input when Part 4 is done! ty

**Comment by alexdseo** [comment]
Data cleaning needed for geo-parsed dataset

**Comment by alexdseo** [comment]
Done & code added at [Geoparsing code](https://github.com/alexdseo/Visualization-App-on-World-Events/blob/master/geoparsing.ipynb)

[csv result](https://github.com/alexdseo/Visualization-App-on-World-Events/blob/master/geoparse.csv)
